// Generated by CoffeeScript 1.8.0
(function() {
  var Analytics;

  Analytics = (function() {
    function Analytics(client) {
      this.client = client;
    }

    Analytics.prototype.search = function(engineName, params, callback) {
      return this.client.get("/engines/" + engineName + "/analytics/search", params, callback);
    };

    Analytics.prototype.autocomplete = function(engineName, params, callback) {
      return this.client.get("/engines/" + engineName + "/analytics/autocomplete", params, callback);
    };

    Analytics.prototype.searchClick = function(engineName, params, callback) {
      return this.client.get("/engines/" + engineName + "/analytics/search_click", params, callback);
    };

    Analytics.prototype.autocompleteClick = function(engineName, params, callback) {
      return this.client.get("/engines/" + engineName + "/analytics/autocomplete_click", params, callback);
    };

    return Analytics;

  })();

  module.exports = Analytics;

}).call(this);
