// Generated by CoffeeScript 1.8.0
(function() {
  var Analytics, Client, Collection, Document, Engine, Tinysou;

  Client = require('./client');

  Engine = require('./engine');

  Collection = require('./collection');

  Document = require('./document');

  Analytics = require('./analytics');

  Tinysou = (function() {
    function Tinysou(token) {
      this.token = token;
      this.client = new Client(this.token);
      this.engines = new Engine(this.client);
      this.collections = new Collection(this.client);
      this.documents = new Document(this.client);
      this.analytics = new Analytics(this.client);
    }

    Tinysou.prototype.search = function(engineName, searchInfo, callback) {
      return this.client.post("/engines/" + engineName + "/search", searchInfo, callback);
    };

    Tinysou.prototype.autocomplete = function(engineName, autocompleteInfo, callback) {
      return this.client.post("/engines/" + engineName + "/autocomplete", autocompleteInfo, callback);
    };

    return Tinysou;

  })();

  module.exports = Tinysou;

}).call(this);
